# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4cb8c773be7b194b2ef7d792b890c5b90467d5314a87b40b4f8d420620ca4f9a9a32b41fab7783d7fb64fa9742d73cf0275274423335313cf8081b4a60842b1

test:
  secret_key_base: 44ad53da1e38b8401328e8898dd54e21ad4a8f4f7064864f17b7988f52a36dbe6759b87f3089204bf87deaee3d20af9816737c9890baa6bfbf8647d6637e4424

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
